- cputree.c
- irqbalance.1
- irqbalance.c
Hi Neil,
I've fixed a few minor things reported in redhat.bugzilla.com.
Thanks,
Petr
> irqbalance minor fixes

- classify.c
Current irqbalance uses PCI class code to determine the irq class
for each of devices. This logic could work well on most of devices.
However, the problem is, there are some PCI devices don't follow
the PCI spec. That caused the improper irq class code assigned to
these devices. Usually, it is hard to ask HW/FW vendors to fix this
kind of bug. Some of those are not bugs, because some new PCI class
code were not defined before the new devices shipment. At same time,
it is very difficult to force a device firmware upgrade even if the
new firmware fix is available for users.
As a correct irq class is crucial for interrupt balance efficiency
and performance, we need some software workarounds for these devices.
This is also what Linux kernel PCI code does in practice.
Signed-off-by: Yong Yang …
> Support PCI quirks in classify code

- classify.c
When irqbalance calls add_missing_irq, usually these irqs don't
have the sysfs entries. This will cause file open errors in PCI
classification code of add_one_irq_to_db.
Before PCI quirk support in v1.0.9, the error was sliently ignored.
But after that, the file open error will be found in --debug output.
This fix skips the PCI irq classification when irqs have no sysfs
entries. The IRQ_OTHER will be used for these irqs, which are same
with old behaviors.
Signed-off-by: Yong Yang <yangoliver@gmail.com>
> Use NULL devpath when irq has no sysfs entries

- classify.c
- irqbalance.h
- procinterrupts.c
merging rudimentary arm support
> Arm support

- cputree.c
props Thomas Lendacky
Closes #50
> Fix assigning IRQ affinity on the wrong NUMA node

- README.md
The title is a question so I am not sure where to add the badge.
> Adding Travis bagde

- index.html
For sure I am not a sitebuilder.
> Add Travis bagde to homepage

- configure.ac
This pull request fixes the logic of two configure options.
> Two configure.ac fixes

- irqbalance.c
- ui/irqbalance-ui.c
Signed-off-by: Kairui Song <kasong@redhat.com>
> Don't leak socket fd on connection error

- misc/irqbalance.service
Reverts Irqbalance/irqbalance#86
> Revert "systemd: add prefixed with "-" to EnviromentFile."

- activate.c
the variable valid_mask and some judgement seems unnecessary.
sign_off_by: Shuang Xia <xiashuang1@huawei.com>
> after Irqbalance@dcc411e, the activate_mapping function seems a little redundancy, 

- irqbalance.c
currently, in scan, irqbalance compare sleep_interval's address to decide if sleep_interval is changed, accutually this judgement is always false now.
sign_off_by: Shuang Xia <xiashuang1@huawei.com>
> fix sleep interval when sleep_interval is changed by socket

- irqbalance.c
solve problem: The pid file generates too late when the
system processes many irqs with using user policy script.
> fix the pid file generates too late when the system processes many irqs with using user policy script

- irqbalance.c
The man doc about realloc() say:
"
If realloc() fails the original block is left untouched; it is not
freed or move
"
So make the handling of realloc() function correctly.
In addition, there is another problem about parameter using in
sock_handle(), it should be use the address of @setup instead of @setup.
> correct to use realloc() function

- irqbalance.c
> fix resource leak on the error paths in main()

- classify.c
- cpumask.h
- cputree.c
- irqbalance.c
- irqbalance.h
- numa.c
- placement.c
- procinterrupts.c
use NUMA_NO_NODE macro instead of -1 for numa
use num_online_cpus() instead core_count
> use NUMA_NO_NODE macro and num_online_cpus() instead

- activate.c
When echoing a mask to /proc/irq/N/smp_affinity make sure to activate
only CPUs which are online. Activating a CPU which is not online results
in a EOVERFLOW.
Originally fixed in Debian by Helge Deller <deller@gmx.de>.
> activate_mapping: activate only online CPUs

- constants.h
- cputree.c
- irqbalance.1
- misc/irqbalance.env
Add IRQBALANCE_BANNED_CPULIST to env file
Remove IRQBALANCE_BANNED_CPUS environment variable
Remove some unused constant macros in constants.h
> Add IRQBALANCE_BANNED_CPULIST to env file and remove some codes

- classify.c
Add log for hotplug appropriately, and delete the useless printf code.
> Add log for hotplug appropriately

- procinterrupts.c
I find some irqs are not banned when I use --banmod. Because the irq desc name in AARCH64 contains space, for example:
43:          1          0          0          0   ITS-MSI 16384 Edge      PCIe PME, aerdrv, pciehp
info->name is "pciehp", so check_for_module_ban returns 0 when I use "--bannmod=aerdrv"
> Fix irqbalance cannot obtain the full name of irq

- classify.c
https://github.com/Irqbalance/irqbalance/issues/202
Signed-off-by: Chao Liu <liuchao173@huawei.com>
> get irq->module relationship from /sys/bus/pci/*/driver

- ui/ui.c
https://github.com/Irqbalance/irqbalance/issues/218
> irqbalance-ui: move 'ASSIGNED TO CPUS' to the last column

- ui/ui.c
> fix memory leak in ui/ui.c

- ui/helpers.c
- ui/irqbalance-ui.c
- ui/irqbalance-ui.h
- ui/ui.c
- ui/ui.h
support using Up, Down, PageUp, PageDown to scroll in view mode
support using Up and Down in edit mode
https://github.com/Irqbalance/irqbalance/issues/217
> irqbalance-ui: support scroll under tui mode of irqbalance-ui

- irqbalance.c
https://github.com/Irqbalance/irqbalance/issues/228
> irqbalance: check the length of optarg

- ui/ui.c
get irq name from /proc/interrupts
> irqbalance-ui: display irq name in SETUP IRQS

- classify.c
Hello,
I would like to start by saying thank you for maintaining such an awesome tool!
Anyways, I am opening an issue and also proposing a possible patch here. Apologies if I should have gone to open an issue first.
For background, I had been having issues with the `banmod` argument and was tracking issue #202 . When I saw that it was patched with PR #208 , I thought I would give it a whirl. While I am sure that the #208 helped most folks, I was still seeing irq's from a banned module being balanced. The reason being that the irq's in question are not in an entry in `/sys/bus/pci/devices`. In other words, from my understanding, #208 introduces an additional check which tries to get the module name for the irq by looking in `/sys/bus/pci/devices/*/interrupts`,  unfortunately for me, the …
> Ensure --banmod is respected

- procinterrupts.c
> irqbalance: fix a minor typo

- thermal.c
https://github.com/Irqbalance/irqbalance/issues/242
> change  the log level in thermal.c from error to warning

- configure.ac
> updating to version 1.9.2

- irqbalance.h
> filter console only output when using journal mode

- bitmap.h
- classify.c
- irqbalance.c
- numa.c
- ui/helpers.c
- ui/helpers.h
- ui/irqbalance-ui.c
- ui/ui.c
- ui/ui.h
It ends up being treated as a char anyway.
> ui: change void to char

- ui/ui.c
> use g_strdup_printf
