Irqbalance/irqbalance

classify.c
types.h

Current implementation just treats all serial bus devices as legacy
devices, and use IRQ_LEGACY by default. But in fact, some serial
bus controller like USB, Fiber Channel, InfiniBand are high speed
and high interrupt rate devices, which are similar with ethernet or
storage devices. On my server with 6 Fiber Channel devices, all these
devices interrupts could be bound to single CPUs under heavy work
load(24Gbps Throughput). That caused serious performance issue. But
if we classify all Fiber channel devices as storage class, which uses
CORE_LEVEL by default, it could fix the problem by balance interrupt
load among multiple cores.
This fix uses PCI sub-class code to classify all serial bus devices,
instead of just using major PCI class code.
Here are the major changes,
a. For USB devices, …

Classify PCI Sub-Class for better performance

---

activate.c
types.h

Only warn once for affinity hint subset empty irqs
https://bugzilla.novell.com/show_bug.cgi?id=893478

bug-893478_warn-once

---

classify.c

Original code used an old PCI-SIG spec for PCI class code definition:
"PCI Local Bus Specification Revision 3.0". In fact, the PCI class
code definition in this spec has been obsoleted for a long time.
Today, PCI-SIG uses a separate spec for PCI class code definition:
"PCI Code and ID Assignment Specification v1.5".
Without the fix, it is possible that new PCI devices are classified
incorrectly by irqbalance code. Two major codes and one sub-class code
were added in the change.
Signed-off-by: Yong Yang <yangoliver@gmail.com>

Follow latest PCI class code spec

---

bitmap.c
bitmap.h
cpumask.h
cputree.c
irqbalance.c

These patches add code to parse /proc/cmdline, extract the isolcpus= argument, and automatically add those isolated cpus to the banned_cpus mask.
This ensures that IRQs will not get assigned to CPUs that are supposed to be isolated from system activity.

automatically add isolated cpus to banned_cpus

---

classify.c

Commit 37c1f simplified sort_irq() logic, but it introduced some unintended
ordering behavior.
I found it by adding two debug messages into migrate_overloaded_irqs() and
move_candidate_irqs() that show the results of sort_irq() as follows:
[Correct case]:
migrate_overloaded_irqs(): obj_type 0 number 3
move_candidate_irqs(): Irq  68 class 4 load 3870960 irq_info 0x0x26210d0
move_candidate_irqs(): Irq  71 class 4 load 3225800 irq_info 0x0x2621e20
move_candidate_irqs(): Irq  63 class 4 load 2903220 irq_info 0x0x261faa0
[Incorrect case]:
migrate_overloaded_irqs(): obj_type 0 number 0
move_candidate_irqs(): Irq  77 class 4 load 4347820 irq_info 0x0x262e050
move_candidate_irqs(): Irq  69 class 4 load 1 irq_info 0x0x2621540
move_candidate_irqs(): Irq  61 class 4 load 5652166 irq_info 0x0x261f1c0 …

Fix sort_irqs() logic

---

configure.ac

libsystemd-journal has been merged in libsystemd at version 209
(2014-02-20), make the configure search for that "new" library.
Closes: #33

Search for libsystemd instead of libsystemd-journal

---

classify.c

x86/x64: Exclude devices with legacy IRQ 255

---

irqbalance.c

There was no easy way to find current version.
This change is quite simple, so any suggestions are welcome.
Maybe add the commit hash?

Add "--version|-V" command line option to get irqbalance's version

---

cputree.c
irqbalance.c
irqbalance.h
numa.c
types.h

The Intel Cluster on Die topology breaks an existing assumption in irqbalance about the structure of the cpu and memory topology.  In CoD, it's possible for a physical package to have multiple NUMA domains.  In that case, irqbalance incorrectly constructs the topology in a way that strands one of the NUMA nodes.  This patch attempts to fix the problem by allowing NUMA nodes to point to the first portion of the CPU hierarchy where they are the unique.  At least with systems that the submitter has tested on, this turns out to be the LLC.

Teach irqbalance about Intel CoD

---

configure.ac

That way we take possible separate tinfo lib into account.
Otherwise the following happens when ncurses was built with separate tinfo library:
```
libtool: link: x86_64-pc-linux-gnu-gcc -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -march=native -mtune=native -O2 -pipe -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -o irqbalance-ui ui/helpers.o ui/irqbalance-ui.o ui/ui.o  -Wl,--as-needed -lglib-2.0 -lcurses -lm -lnuma
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ui/ui.o: undefined reference to symbol 'nodelay'
/lib64/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:564: irqbalance-ui] Error 1
```

Prefer pkgconfig to check for ncursesw.

---

index.html

> `ga('create', 'UA-26' + '87' + '19-3', 'auto');`
There are reverse-search databases for UA numbers. (`https://www.domainiq.com/reverse_analytics`)

Change to Universal Analytics on the homepage

---

classify.c
irqbalance.c
procinterrupts.c

the scanning code for /proc/interrupts has an issue whereby, if the system doesn't contain a pci bus, all other interrupts are skipped in their addition to the irq database.  This means nothing gets balanced, and we constantly just rescan.  This is often a problem on small aarch64 systems, which often don't have a pci bus.  This branch fixes that by always adding the non - pci bus interrupts to the db.  It also does some cleanup of the aarch64 irq class guessing code while I'm in there.

clean up aarch64 irq class guessing and pci bus skipping

---

misc/irqbalance.service

See individual commit messages.
---
The sandbox is not perfect: if an attacker gains arbitrary code execution in `irqbalance`, they can still, for example, read any file owned by root¹ (`/etc/shadow`, `/etc/ssh/ssh_host_rsa_key`, etc.) and encode it inside files in `/proc/irq`², where another unprivileged process also controlled by the attacker could read it and publish it over the network. But I think the unit file would become too unwieldy if we added too many more directives – this should already provide a lot of protection at little cost.
¹: Without `CAP_DAC_READ_SEARCH`, it can’t read files that are owned by other users and not world-readable (e. g. stuff in `/home`), but files owned by root can be read without any special capabilities.
²: The kernel won’t let you create arbitrary …

Service file improvements

---

classify.c
irqbalance.1
irqbalance.c
irqbalance.h
procinterrupts.c
ui/irqbalance-ui.c

This feature enhances our policy script feature.  Currently irqbalance has the ability to use a single policy script, which must contain the logic to properly handle/ignore all devices, which is less than ideal.  This feature enhances policyscripting to allow for a directory to be specified that holds multiple scripts, that can control individual devices.  The idea being that if a IHV creates a device that needs special irqbalance policy, they can submit a script for inclusion that detects only their device and handles it accordingly.

Expansion of policy scripting

---

irqbalance.c
ui/irqbalance-ui.c
ui/ui.c

Some memleak issues is found by static analysis tools, and can confirm
irqbalance is leaking memory slowly when there are incomming connection
to socket.
This patch could solve the memleak problem.

Fix several memleak problems found by covscan

---

ui/irqbalance-ui.c
ui/irqbalance-ui.h

irqbalance ui is faling due to the changes in commit 19c25dd.
This patch align irqbalance-ui's socket connecting routine with
irqbalance.c

Fix irqbalance ui failing to connect to irqbalance daemon

---

irqbalance.c

Got:
"specified bound 2048 exceeds the size 19 of the destination"
when -O2 is used, and a "*** buffer overflow detected ***" error output
with no backtrace.
With -O0, it's gone, guess it's some gcc optimization problem, and the
size there is wrong anyway, this patch could fix it.

Fix an possible overflow error

---

classify.c
irqbalance.1

Currenly irqbalance require custom scirpts to be executable. If a
non-executable file is found, irqbalance will stil try to execute it but
fail with no permission error.
So just ignore non-executable file, this also make is possible to have
non-executable files in policyscript directory as reference.

policyscript: ignore non-executable files when specifying a directory

---

procinterrupts.c

In current /proc/interrupts, the 'xen-dyn-event' was split to 'xen-dyn    -event'.
It causes interrupts not balanced inside xen guest.
Below result is without this patch:
70:         29          0          0          0   xen-dyn    -event     vif0-q0-tx
71:        120          0          0          0   xen-dyn    -event     vif0-q0-rx
72:     586350          0          0          0   xen-dyn    -event     vif0-q1-tx
73:         44          0          0          0   xen-dyn    -event     vif0-q1-rx
74:         19          0          0          0   xen-dyn    -event     vif0-q2-tx
75:        179          0          0          0   xen-dyn    -event     vif0-q2-rx
76:         67          0          0          0   xen-dyn    -event     vif0-q3-tx
77:     299637          0          0          0 …

procinterrupts: check xen-dyn-event more flexible

---

cputree.c
numa.c

The code used to use strstr(..., "node") while iterating over
sysfs directories such as /sys/devices/system/cpu/cpu*.
It then made an assumption that the entry would start with "node",
which is not necessarily the case (e.g. the "firmware_node" entry).
The code happened to work for as long as the node[0-9]* entry
would be processed before the "firmware_node" entry shows up.
A change to the linux kernel "end_name_hash" function resulted
in a different hash, and ultimately in a different order
by which entries were returned by readdir(3).
This led to the exposure of this bug.
Signed-off-by: Gerd Rausch <gerd.rausch@oracle.com>

Fix ambiguous parsing of *node* entries in /sys.

---

misc/irqbalance.service

- When failing to read the env file, do not judge it as a failure.
- https://www.freedesktop.org/software/systemd/man/systemd.exec.html
It is intended to prevent errors from forgetting to fix the file path as it is.
This is because we think that importing EnvironmetFile is not mandatory.

systemd: add prefixed with "-" to EnviromentFile.

---

irqbalance.c
ui/irqbalance-ui.c

This fixes string truncation warning generated by GCC of the form:
irqbalance.c:485:2: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
strncpy(addr.sun_path, socket_name, strlen(socket_name));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using source size in strncpy so fix that by using destination size.
For the instance of this issue in irqbalance-ui.c, fix the issue by
eliminating the unneeded temporary buffer.
Signed-off-by: Sekhar Nori <nsekhar@ti.com>

Fix string truncation issues detected by GCC 8

---

cputree.c
placement.c

Discovered a bug in which, when numa isn't available we failed to assign
the unspecified node to the device tree, leading us to not balance any
interrupts.  Make sure it gets added so irq get parsed down through the
tree to the proper topology node
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

fix balancing when numa information isn't available

---

irqbalance.1

There is no declaration about how irqbalance deal with isolated CPUs or
adaptive-ticks CPUs, and how IRQBALANCE_BANNED_CPUS will override the
behavior of auto-banning of such CPUs. Refine the document to avoid
confusion.
Signed-off-by: Kairui Song <kasong@redhat.com>

Refine document about IRQBALANCE_BANNED_CPUS

---

irqbalance.1

Just noticed this waning in a manpage scan report, trivial but let's
fix it.
Signed-off-by: Kairui Song <kasong@redhat.com>

Remove a duplicated word in manpage

---

procinterrupts.c

The word blacing should be blancing
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>
Reported-by: Edward Arthur <ed.arthur@gmail.com>

Fix typo in procinterrupts

---

classify.c

Currently user-defined policies against non-PCI devices' interrupts
are not working properly.
For example, when trying to set "balance_level=core" for a non-PCI
device interrupt which is classified as "other", will result in
the level of "package" because overrided in add_new_irq().
This patch fixes this by restricting irq info initializations in
add_one_irq_to_db(), which requires a change on its parameters.
Signed-off-by: Shuang Xia <xiashuang1@huawei.com>
Signed-off-by: Yun Wu <wuyun.wu@huawei.com>

use policy prior to the default values

---

procinterrupts.c

in aarch64, irqbalance will guess irq's class and type according to
irq's name, but it did't work properly now, a irq's name will be
matched twice and class will always be IRQ_OTHER. such as a nic
interrupt, the debug log will be:
IRQ eth3-tx0 (109) guessed as class 5
IRQ eth3-tx0 (109) guessed as class 0
irq's class should be IRQ_GBETH but is IRQ_OTHER.

fix guess_arm_irq_hints

---

activate.c
cputree.c
procinterrupts.c

getline() will return -1 when fail, so make the return value handle
correct.

make the return value of getline() handled correct

---

classify.c

keep the parameters 'path' of check_for_irq_ban function consistent with line 699.
In check_for_irq_ban,
sprintf(cmd, "%s %s %d > /dev/null",banscript, path, irq);
the banscript is unique, so i think the path should keep consistent.

change path to devpath

---

procinterrupts.c

The local variable @savedline[1024] is unused in parse_proc_interrupts(),
so delete it.

delete unused local variables in parse_proc_interrupts(), and checking return value of strdup() in collect_full_irq_list()

---

numa.c

when getline() fail, the memory still need to be freed.

free the memory when getline() fail in add_one_node()

---

classify.c
cputree.c
irqbalance.c
ui/irqbalance-ui.c

There are several places where memory allocation does not check return
values, adding null pointer checks.

prevent NULL pointer dereference when memory allocation failure

---

activate.c
classify.c
cputree.c
irqbalance.h
numa.c

There are some redundant codes about file processing which with the same
logic. so abstract the same logic to the one function, and invoke it
where it need.
A different is that in add_one_node(), not return if fopen() fail, and
remove the ferror() judgement, I think it has no effect.

reduce redundant code for file processing

---

classify.c

If devpath is NULL, read devpath/numa_node and devpath/local_cpus will fail. So just skip it. The old code won't cause any bugs.

when devpath is NULL, skip reading files

---

procinterrupts.c

in parse_proc_interrupts, just get irq's name. After "*c = 0", characters after ":" in line and c are useless. There is no need to let c increase.

remove "c++;" in parse_proc_interrupts

---

classify.c

reduce redundant check in add_missing_irq()
delete the useless free for banned_irqs in free_cl_opts()

reduce some redundant codes in add_missing_irq()  and free_cl_opts()

---

procinterrupts.c

irqbalance: use isdigit() instead of the logic of character judgment

---

cputree.c

Resource is freed by traversing each list in clear_cpu_tree(), which can
be replaced by g_list_free_full(), so make the code simpler.
In addition, the children and numa_nodes list of cpus is empty, so
free_cpu_topo() also free the list for cpus have no impact.

irqbalance: use g_list_free_full() in clear_cpu_tree()

---

classify.c
cputree.c
irqbalance.h
numa.c
procinterrupts.c

remove unused package_count variable
modify the order of input parameter for calloc()
use g_list_find() instead of the search logic for cpu_topo

some clean codes about cputree for irqbalance

---

cputree.c
irqbalance.c
irqbalance.h
numa.c

add_cpu_to_cache_domain() will return NULL if memory allocation failure,
so check the return value before invoking add_cache_domain_to_package().

irqbalance: prevent NULL pointer dereference in do_one_cpu()

---

cputree.c

The local variable package_mask is used without initialized. add
cpus_clear(package_mask) before using.
In addition, the variable cache_mask is called cpu_set() twice, which
is unnecessary, so delete the redundant code.

irqbalance: initialize package_mask before using in do_one_cpu()

---

cputree.c
irqbalance.h
numa.c

Use add_one_node(NUMA_NO_NODE) to create a unspecified node instead of
global variable.
It can reuse the function add_one_node() and delete two global variable
unspecified_node_template and unspecified_node. Also it can reuse the
function free_cpu_topo() instead of free_numa_node().

irqbalance: use add_one_node() to create unspecified node for numa

---

cputree.c
irqbalance.c

The memory of cpu_ban_string was release in sock_handle function,
so the banned_cpumask_from_ui will dereference an invalid memory.
Fix this issue by delay release memory.
Reproduce:
echo "settings cpus 0-3" | nc -U `find /var/run/irqbalance/ -name *sock`
Signed-off-by: Weiping Zhang <zhangweiping@didiglobal.com>

fix invalid pointer dereference banned_cpumask_from_ui

---

classify.c
cputree.c
irqbalance.h

irqbalance: use process_one_line() instead of fscanf()
irqbalance: remove redundancy check in add_one_irq_to_db()

use process_one_line() instead of fscanf() and remove redundancy check in add_one_irq_to_db()

---

irqbalance.c

polscript is alloced in parse_command_line and isn't freed when irqbalance exit

free polscript if irqbalance exit

---

classify.c

There are some same logic codes in build_one_dev_entry() that can be
replaced by add_new_irq().

irqbalance: use add_new_irq() instead of the same logic

---

cputree.c
irqbalance.c

if we free cpu_ban_string in setup_banned_cpus, when the next time we enter setup_banned_cpus by other causes, banned_cpus will be overrided by getenv("IRQBALANCE_BANNED_CPUS") or nohz_full | isolated_cpus. So we free cpu_ban_string when the next request come, keep banned cpus in cpu_ban_string  and banned_cpumask_from_ui, and parse banned_cpumask_from_ui it every time we enter setup_banned_cpus.
When we send "settings cpus NULL", we also need to set need_rescan to 1, otherwise we cannot enter setup_banned_cpus to override banned_cpus and it will keep the old value.

free cpu_ban_string when the next request come

---

irqbalance.c
irqbalance.h
irqlist.c

The current irq migrating rule can't migrate irqs in some scenes,  which can lead one cpu irq load closer to 100%. For example:
CPU0   CPU1  CPU2
irq0  50%     0%      0%
irq1  50%     0%      0%
irq3   0%      10%     0%
irq4   0%      0%       5%
total  100%  10%     5%
In the above scenes, the CPU0's irq load is too high, however the other cpus'   irq load is  very low.
By the old irq migrate rule, the irqs cannot be moved if the adjustment_load will become smaller than
the min_load after moving irq. However, we can accept that the delta load become smaller after moving irq. With the new migrating rule(migrate_ratio=2), the above cpu irq load can become much lower:
CPU0   CPU1  CPU2
irq0  50%    0%      0%
irq1  0%      0%      50%
irq3   0%    10%     0%
irq4   0%     0%      5%
total …

improve irq migrating rule to avoid high cpu irq load

---

activate.c
classify.c
irqbalance.h

For aarch64, the PPIs format in /proc/interrputs can be parsed and add to interrupt db, and next, the number of interrupts is counted and used to calculate the load. Finally these interrupts maybe scheduled between the NUMA domains.
Acctually, the PPIs cannot change aff, and it should not be added to interrupt db. This patch fix it.
Add a check before add a interrupt to db, just only reads the irq's aff, and write it back to avoid any impact on the system, According to the result of writing to fitler the irq.

arm64: Add irq aff change check

---

irqbalance.h

SOCKET_TMPFS is defined as "/run/irqbalance/", which is used in irqbalance.c init_socket():
- snprintf(socket_name, 64, "%s/%s%d.sock", SOCKET_TMPFS, SOCKET_PATH, getpid());
so the third "/" in SOCKET_TMPFS is redundant.
it won't cause any bug, i just think it would be better to keep same as SOCKET_TMPFS defined in ui/irqbalance-ui.h

remove redundant "/" in SOCKET_TMPFS

---

cputree.c

When the environment variable IRQBALANCE_BANNED_CPUS is not specifily
the cpu, we expect do not place IRQs on CPUs the kernel keeps isolated
or nohz_full.
But currently, it will go to call cpumask_parse_user and ignore the
isolated or nohz_full. so add strlen checking before calling
cpumask_parse_user.

Add strlen checking for IRQBALANCE_BANNED_CPUS

---

irqbalance.c

Currently parse_command_line() implements the arg parsing function,
but if HAVE_GETOPT_LONG is not defined, the arg parsing detail is
in main() funtion.
So put the arg parsing detail into parse_command_line() is more
clearly.

put arg parsing detail into parse_command_line()

---

cputree.c
irqbalance.1

allows banning of cpus using the taskset cpulist syntax in addition to the
bitmap syntax supported via the existing environment variable
IRQBALANCE_BANNED_CPUS

add env variable to ban cpus using cpulist syntax

---

cputree.c

https://github.com/Irqbalance/irqbalance/issues/159
recently brought to our attention that online cpu status isn't functional on all
arches.  Specifically on parisc, the availability of
/sys/devices/system/cpu/cpu<N>/online is in question.  The implication here is
that its not feasible to accurately determine cpu count, and as a result,
irqbalance doesn't work on that arch
Fix it by changing our online detection strategy.  The file
/sys/devices/system/cpu/online is a cpulist format file that seems to be present
accross all arches and configs.  As such, we can use this file to determine
online status per cpu reliably.
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

Adjust how we determine if a cpu is online

---

irqbalance.1

Add some example for IRQBALANCE_BANNED_CPUS make it easier to understand how to use it.

Add some examples for IRQBALANCE_BANNED_CPUS

---

cputree.c

When the banded CPU is configured, and the "isolcpus" or "nohz_full"
is configured, the log for isolated and nohz CPUs are not correct.
So only log relevant infomation when isolcpus and nohz_full has been
handled, also put the cpus_clear() closer.

log correctly for isolated and nohz_full cpus

---

classify.c
irqbalance.c
irqbalance.h
procinterrupts.c

When new irqs added to the system, irqbalance will need to rescan for rebalancing.
The rescan operation exists the following problems:
1. When there existing many irqs to balance, the rescan operation will cost much time.
2. The rescan operation will produce irq migration with a high probability, which can make irq data cold, and affect the system performance.
To avoid the above problems, we provide the irq hotplug feature for irqbalance. 
When we find new irqs during reading "/proc/interrupts", then we add the new irqs to interrupts_db,
and place them in rebalance irq list. 
The irq hotplug feature for irqbalance can rebalance new irqs quickly without irq migration.We have used the irqbalance hotplug feature in our product for many years.It brings high performance to us when occuring irq …

Add irq hotplug feature for irqbalance

---

classify.c
irqbalance.h
procinterrupts.c
types.h

The pci devices can be hot pulled from the system, and the corresponding irqs will be  deactive. By add the irq hot pull method, we can manage irqs  more efficiently with less resource consumption.

Add irq hot pull method for irqbalance

---

classify.c

Followring error is observed on some large servers:
[   40.345505] irq 4: Affinity broken due to vector space exhaustion.
Irq 4 is on node 0 but irqbalance put it in node 1. Root cause is that irq 4 is not an from an PCI device so irqbalance failed to get the right numa node number.
This PR fixes this problem.

Also fetch node info for non-PCI devices

---

cputree.c
irqbalance.c
ui/ui.c

Fixes (on arm 32-bit):
$ irqbalance-ui
Invalid data sent.  Unexpected token: (null)TYPE
And strace showed the following:
237   sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="stats", iov_len=5}], msg_iovlen=1, msg_control=[{cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=237, uid=0, gid=0}}], msg_controllen=24, msg_flags=0}, 0) = 5
237   recv(3, "TYPE 3 NUMBER -1 LOAD 0 SAVE_MODE 0 (null)TYPE 2 NUMBER 0 LOAD 0 SAVE_MODE 0 (null)TYPE 1 NUMBER 0 LOAD 0 SAVE_MODE 0 (null)TYPE 0 NUMBER 3 LOAD 0 SAVE_MODE 0 (null)TYPE 1 NUMBER 1 LOAD 0 SAVE_MODE 0 (null)TYPE 0 NUMBER 1 LOAD 0 SAVE_MODE 0 (null)TYPE 1 NUMBER 2 LOAD 0 SAVE_MODE 0 (null)TYPE 0 NUMBER 2 LOAD 0 SAVE_MODE 0 (null)TYPE 1 NUMBER 3 LOAD 0 SAVE_MODE 0 (null)TYPE 0 NUMBER 0 LOAD 0 SAVE_MODE 0 …

fix uint64_t printf format (use PRIu64)

---

ui/ui.c

Fix start position for the SETTINGS/CPU ban menu.
Fixes (start irqbalance-ui, press F4, press c, press Enter):
$ irqbalance-ui
Segmentation fault (core dumped)
$ gdb irqbalance-ui core
Program terminated with signal SIGSEGV, Segmentation fault.
#0  toggle_cpu (cpu_list=cpu_list@entry=0x90e170,
cpu_number=cpu_number@entry=-1) at ui/ui.c:192
192			entry_data = (cpu_ban_t *)(entry->data);
(gdb) where
#0  toggle_cpu (cpu_list=cpu_list@entry=0x90e170,
cpu_number=cpu_number@entry=-1) at ui/ui.c:192
#1  0x00013d4c in handle_cpu_banning () at ui/ui.c:254
#2  0x0001371c in settings () at ui/ui.c:598
#3  0x0001199c in key_loop (data=<optimized out>) at ui/irqbalance-ui.c:378
#4  0xb6ed9ae8 in ?? ()
For the starting position '5' cpu_number is calculated as '-1'.
Fix the same off by one for the SETUP …

ui: fix cpu/irq menu off by one

---

cputree.c

The input para(path) of do_one_cpu is /sys/devices/system/cpu/cpu$id. When the cpus occur some error, /sys/devices/system/cpu/cpu$id will be diappear, and opendir(path) will return null. Thus, irqbalance will exit with coredump.

Add return value check of opendir in do_one_cpu

---

procinterrupts.c

This recent commit broke compiling on non AARCH64 architectures:
commit d17bcc953c513f93553f531e5444553f2bf6ca46
Author: liuchao173 <55137861+liuchao173@users.noreply.github.com>
Date:   Tue Apr 27 15:36:30 2021 +0800
Fix irqbalance cannot obtain the full name of irq
This results in:
procinterrupts.c:186:11: error: ‘irq_fullname’ undeclared (first use in this function); did you mean ‘irq_name’?
186 |  snprintf(irq_fullname, PATH_MAX, "%s", last_token);
|           ^~~~~~~~~~~~
|           irq_name
procinterrupts.c:186:11: note: each undeclared identifier is reported only once for each function it appears in
This fixes it.
Signed-off-by: Michael Neuling <mikey@neuling.org>

Fix compile issue with none AARCH64 builds

---

classify.c

when a banned irq doesn't exist, it won't be removed from banned_irqs

remove no existing irq in banned_irqs

---

configure.ac
cputree.c
irqbalance.c

Hi,
I think the UI is actually the only user of the socket right?
If the communication socket is added to support the UI, then when UI is not built, also disable the socket, save a bit of resource and improve security.
Or maybe a separate parameter like `--without-socket` is better?

Disable the communication socket when UI is disabled

---

Makefile.am
configure.ac

Use pkg-config to find numa and fallback to current mechanism. Thanks to pkg-config, numa dependencies such as `-latomic` will be retrieved.
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

configure.ac: use pkg-config to find numa

---

classify.c

If Linux maps an IRQ associated with an empty node (hence not exposed
under /sys/devices/system/node/), irq_numa_node(info) will be set to
NULL, leading to a core dump in place_irq_in_node().
Add a warning for this unusual condition and set ->numa_node to the
the default entry.
Signed-off-by: Cédric Le Goater <clg@kaod.org>

irqbalance: Check validity of numa_node

---

procinterrupts.c

When irq name does not contain spaces, savedptr is an empty string and irq_fullname will have a extra space at the end like "LNRO0005:00 ".
So opendir in check_platform_device will fail, and irqbalance prints log:
"No directory /sys/devices/platform/LNRO0005:00 /: No such file or directory"

fix opendir fails in check_platform_device

---

irqlist.c

Min_load, adjustment_load  and load are unsigned integers, so it overflows when (lb_info->min_load + info->load) < (lb_info->adjustment_load - info->load). The result will be greater than zero. Therefore the irq cannot be selected to rebalanced.

fix unsigned integer subtraction sign overflow

---

misc/irqbalance.service

libcapng is issuing an error in the system log when irqbalance attempts
to drop capabilities, but systemd service unit has already done dropped
all capabilities. commit 43751df tried to fix this but it didn't fix it
completely. CapabilityBoundingSet also need to be dropped.
Fixes #182

Drop CapabilityBoundingSet from irqbalance service

---

ui/ui.c

`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:
ui/ui.c:714:16: error: format not a string literal and no format arguments [-Werror=format-security]
714 |         printw(copy_to);
|                ^~~~~~~
Let's wrap all the missing places with "%s" format.

ui/ui.c: always use "%s"-style format for printf()-style functions

---

ui/irqbalance-ui.c

receive data with MSG_TRUNC set so that we can check to see that we got
everything the server sent us.
Signed-off-by: Neil Horman <nhorman@tuxdriver.com>

Ensure that we get all of a unix message

---

Makefile.am
configure.ac
cpumask.h
cputree.c
irqbalance.c
thermal.c
thermal.h

Hello irqbalance folks,
I previously attempted to share this patchset via the mailing list. But
since there has been no feedback, I've decided to give my pull request
here. The patches essentially support interaction with hardware to
determine which CPUs to be masked from IRQ handling. This approach is
different from user-driven CPU masking that is already in irqbalance.
Here is a little bit of background and some details about that.
Appreciate your feedback.
== Thermal Events ==
Intel's Hardware Feedback Interface (HFI) provides a monitoring mechanism
for a CPU's performance and energy efficiency status. A table is shared
between hardware and the operating system. The table is updated as per
operating condition changes, e.g. due to thermal limit.
The table has numeric values to indicate …

Support thermal events

---

irqbalance.c

https://github.com/Irqbalance/irqbalance/issues/214

add keep_going check to prevent irqbalance from failing to exit after SIGTERM

---

procinterrupts.c

The name of an interrupt chip can start with a number, stop before it.

parse_proc_interrupts: fix parsing interrupt counts

---

ui/irqbalance-ui.c
ui/ui.c
ui/ui.h

when invoking setup_irqs in settings or invoking settings in setup_irqs, it
doesn't break but enters another while loop.
For example:
\# gdb program `pidof irqbalance-ui`
(gdb) bt
\# 0  0x0000ffffb0dcc7b0 in poll () from /usr/lib64/libc.so.6
\# 1  0x0000ffffb0e9097c in _nc_timed_wait () from /usr/lib64/libtinfo.so.6
\# 2  0x0000ffffb0ecc154 in _nc_wgetch () from /usr/lib64/libncursesw.so.6
\# 3  0x0000ffffb0eccb18 in wgetch () from /usr/lib64/libncursesw.so.6
\# 4  0x00000000004045d4 in setup_irqs () at ui/ui.c:637
\# 5  0x0000000000404084 in settings () at ui/ui.c:614
\# 6  0x0000000000404084 in settings () at ui/ui.c:614
\# 7  0x0000000000404084 in settings () at ui/ui.c:614
\# 8  0x0000000000404084 in settings () at ui/ui.c:614
\# 9  0x0000000000404084 in settings () at ui/ui.c:614
\# …

irqbalance-ui: can't change window when in editing state

---

ui/ui.c

save space for printing interrupt names
https://github.com/Irqbalance/irqbalance/issues/224

irqbalance-ui: print cpulist in SETUP IRQS

---

cputree.c
irqbalance.1
placement.c

This patch have no functional modification. Just improve the doc and log
for isolcpu, nohz_full and numa node banning cpus, for providing more
info for users.
Signed-off-by: Tao Liu <ltao@redhat.com>

Improve documentation and logging for banned cpus

---

Makefile.am
configure.ac

openwrt would find it useful to have a statically linked version of
irqbalance for better link-time optimization.

Enable static building of irqbalance

---

ui/irqbalance-ui.c

When processing the ',' in hex_to_bitmap, it returns '0000\ 0' directly.
The return value will be freed in parse_setup, but it is not requested
through malloc.
Fixes: 85d37098a551 ("Fix several memleak problems found by covscan")
And it treat ',' as "0000", which cause irqbalance-ui will display wrong
Banned CPU numbers.
For example:
\# IRQBALANCE_BANNED_CPUS="00000002,00000000,00000000" ./irqbalance
or
\# IRQBALANCE_BANNED_CPULIST="65" ./irqbalance
\# ./irqbalance-ui
Banned CPU numbers: 73
Fixes: 76d1c9d73935 ("Add main user interface files")

irqbalance-ui: skip ',' in parse_setup to avoid coredump

---

thermal.c

init_thermal() calls deinit_thermal() on error condition, as well as main() calls deinit_thermal() again, causing a double-free.
Signed-off-by: Dirk Müller <dirk@dmllr.de>

Avoid double free on deinit_thermal()

---

cputree.c

cpu number has already been parsed and saved in cpunr, remove redudant  strtoul().

optimize getting cpu number

---

misc/irqbalance.service

AF_NETLINK is needed for communicating with the thermald daemon, without that the start up logs a warning
thermal: socket bind failed, thermald may not be running.
because systemd prevents access to NETLINK.

allow AF_NETLINK in the systemd service restrictions

---

thermal.c

The commit febe697ac321 ("change the log level in thermal.c from error to warning") happens to insert an unneeded message: "thermald may not be running."
This is not true because the events come from the kernel and Netlink has the multicast subscription model. So it has nothing to do with thermald.
Signed-off-by: Chang S. Bae <chang.seok.bae@intel.com>

thermal: Fix the warning message

---

procinterrupts.c

On arm64 SoCs like TI's K3 SoC and few other SoCs, IRQ names don't get parsed correct due to which they end up being classified into wrong class. Fix this by considering last token to contain IRQ name always.
Eg.: /proc/interrupt
cat /proc/interrupts
CPU0       CPU1       CPU2       CPU3
11:       7155       8882       7235       7791     GICv3  30 Level     arch_timer
14:          0          0          0          0     GICv3  23 Level     arm-pmu
15:          0          0          0          0     GICv3 208 Level     4b00000.spi
16:          0          0          0          0     GICv3 209 Level     4b10000.spi
116:          0          0          0          0  MSI-INTA 1716234 Level     485c0100.dma-controller chan6
134:        166          0          0          0  MSI-INTA 1970707 Level …

procinterrupts: Fix IRQ name parsing on certain arm64 SoC

---

ui/ui.c

Avoid repainting the entire terminal window with black background. Instead, invoke 'use_default_colors' and use color index -1 to keep user-configured background and foreground colors.
For pairs 1, 2, 3, 8, 9, 10, simply change background index to -1. Keep pair 4, but enable the 'bold' attribute for text to improve legibility. For pair 5 (white on red) use default foreground, and instead of pair 6 (red on white) use reverse of pair 5 with bold.
This substantially improves legibility of the UI on a terminal configured with a light background for me.

ui: do not force black background

---

thermal.c

In the log message perf and efficiency fields are swapped. So, showing perf field as efficiency and vice versa. Fix this to show correct log message.
Signed-off-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>

thermal: Fix log message for perf and efficiency

---

misc/irqbalance.service

Modified to start only when there are 2 or more CPUs, as intended in the original pull request (https://github.com/Irqbalance/irqbalance/pull/201).

Fix CPU number condition in service file

---

misc/irqbalance.service

Reverts Irqbalance/irqbalance#257
I was misunderstanding the syntax of the unit file. The original line was reflecting the condition as intended.

Revert "Fix CPU number condition in service file"

---

thermal.c

the handle_error function for thermal should skip EINTR errors, but stop for everything else

Issue 259: select NL_SKIP / NL_STOP based on error

---

procinterrupts.c

```
{NULL} utilises the null pointer, but this is not valid, because null is a pointer:
procinterrupts.c:110:29: error: initialization of 'long unsigned int' from 'void *' makes integer from pointer without a cast [-Werror=int-conversion]
110 |                 { "eth.*" ,{NULL} ,NULL, IRQ_TYPE_LEGACY, IRQ_GBETH },
0-initialisation should be done with '0' instead of a pointer.
```

procinterrupts: fix initialisation of regex_t struct

---

activate.c

Previously irqbalance uses the return value of fprintf() to decide whether the modification of smp_affinity is successful or not. However it is not reliable because fprintf() is stream buffered, a fflush() should be used to check the buffered data been successfully written into the file before the judgement.
This patch fixes the issue by introducing fflush() after fprintf().

activate_mapping: fflush the buffered data to smp_affinity

---

activate.c

Add missing return statement.
Fixes: 470a64b19062 ("activate_mapping: make sure to catch all errors")

activate_mapping: avoid logging error when there is none

---

irqbalance.c
misc/irqbalance.service

This is an alternative to https://github.com/Irqbalance/irqbalance/pull/277

Automatically use systemd journal logging if run under systemd

---

contrib/meson.build

Hi! :wave: 
I package this project for Arch Linux and would be *very much interested* in using meson instead of autotools for packaging! :tada: 
I fixed the build to link against numa, install the man pages and set the correct project version.
I'd be happy if this could be merged and the meson build system files be eventually moved to the root of the repository, so that it is easier to find them (I only now noticed by accident)!

Improvements for meson build system

---

activate.c
irqlist.c
types.h

It is fairly pointless to try migrating an IRQ which is known to be unmigratable.
Instead of using an extra flag, set the `level` to BALANCE_NONE, which shortcuts quite some code, and implicitly also disables the misleading repeated log message:
```
Dez 10 02:52:55 varm irqbalance[828]: Selecting irq 75 for rebalancing
Dez 10 02:52:55 varm irqbalance[828]: Cannot change IRQ 75 affinity: Input/output error
Dez 10 02:52:55 varm irqbalance[828]: IRQ 75 affinity is now unmanaged
...
Dez 10 02:52:55 varm irqbalance[828]: Selecting irq 75 for rebalancing
...
Dez 10 02:52:55 varm irqbalance[828]: Selecting irq 75 for rebalancing
```

Slience "... rebalancing" messages for unmigratable IRQs

---

activate.c

if the fopen fails, errsave is used uninitialized
https://github.com/Irqbalance/irqbalance/issues/287

activate_mapping: set errsave before first jump to the error label

---

activate.c

An IRQ may be migrated several times during one loop iteration, and end up with the same CPU affinity mask as before - the "moved" flag is merely a hint a affinity change may be necessary. This notably also happens during initial placement, but may happen also anytime later.
To avoid visiting each IRQ again and again unset the "moved" flag. This avoids the open/stat/read/close syscalls for unchanged interrupts.
Fixes: #285

Avoid repeated affinity checks when no change is necessary

---

irqbalance.c

Instead of sleeping in scan() and blocking the main loop, return and let the main loop call back scan().
Quickly tested (long running daemon and one shot), it seems to works
Fix #298

Fix socket API being blocked for 10s

---

ui/irqbalance-ui.c

A negative index will be used when recv() fails, which is unexpected for the data buffer.

irqbalance-ui: check if using a negative index of buffer

---

activate.c

Since `fprintf()` may buffer output, as noted in 470a64b19062, `fclose()`'s error value was also being checked for the write errors.  However in 8d7c78304fb9 an `fflush()` was added in between meaning that these buffered write errors were again unchecked.  Some actual errors were not being logged, in my case `-ENOSPCs`.
Make the fclose and fflush branches look similar.
Fixes: 8d7c78304fb9 ("Flush file before closing")

Check `fflush()` return value

---

.github/workflows/meson.yml

tests old and new Clang/GCC on x64 and Alpine Linux on various platforms.
Sample run:
https://github.com/neheb/irqbalance/actions/runs/8513901951

CI: add meson CI

---

activate.c
classify.c
cputree.c
irqbalance.c
irqbalance.h
irqlist.c
placement.c
types.h

This is a proposed fix for https://github.com/Irqbalance/irqbalance/issues/303 up for discussion.  Here's the relevant commit msg:
---
There are situations where irqbalance may try to migrate large numbers of
IRQs to a topo_obj, there's no upper bound on the number as the
placement logic is based on load mainly.  The kernel's irq bitmasks limit
the number of IRQs on each cpu and if more are tried to be migrated, the
write to smp_affinity returns -ENOSPC.  This confuses irqbalance's
logic, the topo_obj.interrupts list no longer matches the irqs actually
on that CPU or cache domain, and results in floods of error messages.
See https://github.com/Irqbalance/irqbalance/issues/303 for details.
For an easy fix, track the number of IRQ slots still free on each CPU.
We start with INT_MAX meaning …

Try fix https://github.com/Irqbalance/irqbalance/issues/303

---

cputree.c
irqbalance.c
ui/helpers.c
ui/irqbalance-ui.c
ui/ui.c

clang-tidy and g_ API conversions

---

irqbalance.c

Previously invoke irqbalance with --version options, the return value is 1 instead of 0:
$ irqbalance --version
irqbalance version 1.9.4
$ echo $?
1
It is unexpected because irqbalance have successfully returned the version string with no errors, so 0 should be returned instead of 1. This will confuse some automation tests.
This patch will make irqbalance return the correct value for version option.

Version option should return 0 rather than 1

---

misc/irqbalance.env

Systemd now logs when a variable expanded in a unit file is not explicitly defined. Thus, in the systemd service when we expand the variable a warning is logged https://github.com/Irqbalance/irqbalance/blob/master/misc/irqbalance.service#L11. This behavior was introduced to systemd in versions 254+ https://github.com/systemd/systemd-stable/commit/f331434d13488425ccd8485327085d15f8f92aea
Squelch this warning by uncommenting IRQBALANCE_ARGS in irqbalance.env, instead setting it to the empty string.
Addresses https://github.com/Irqbalance/irqbalance/issues/321

Define IRQBALANCE_ARGS as empty string to squelch systemd warning

---

irqlist.c

In migrate_irq(), the list will not be changed if info not found.

Check info->moved before updating

---

placement.c
ui/irqbalance-ui.c
ui/ui.c

-Wfanalyzer complains about null pointer dereferences. Check for them.
Interestingly I see do loops in quite a few places.

fix some GCC fanalyzer warnings

---

irqbalance.c

When using the API to ban cpus or irqs, the command can easily be longer than 500, so increase the buffer to 16384, which fits ~3250 cpus or irqs, and add a check to log and exit if it is still not enough.
I went the simple route of just bumping the buffer size, tell me if you prefer a recvmsg + realloc loop or ...

Check API command length, allow up to 16384

---

procinterrupts.c

The default length of path is 512, but the strcat() is used without check if path is overflowed, otherwise a segfault is observed on some aarch64 machines. This patch will use snprintf instead of strcat for the buffer length checking.

check_platform_device: Check the length of path

---

procinterrupts.c

Commit da75aae4effd ("conver strncmp to g_str_has_prefix") introduced an error which reversed the string existence checking condition.
Before that commit, the check condition is:
(strncmp(name, "Level", len) == 0 || strncmp(name, "Edge", len) == 0)
After that commit, the check condition is equal to:
(strncmp(name, "Level", len) != 0 || strncmp(name, "Edge", len) != 0)
This is unexpected and let's fixe this error.

Fix the wrong string existence checking condition

---

Makefile.am
configure.ac
meson.build
meson_options.txt
misc/irqbalance.service.in

Having two EnvironmentFile key words to get replace due to a recent irqbalance.service change, got silently wrong by an sed replacement of config paths...
These 2 patches unify and enhance the meson and autoconf build setup and make the 2 EnvironmentFile directories configurable.

Properly embed EnvironmentFile and unify meson and autoconf build env

---

procinterrupts.c

Apologies, I was hit by a temporary bout of stupidity and forgot that strnprintf() returns the number of bytes that would be written if the buffer was sufficient, not the real number of bytes written - so its result may be larger than PATH_MAX and must be compared using >=, not ==.

Fix a typo/thinko in fix to check_platform_device()
